apiVersion: v1
kind: ConfigMap
metadata:
  name: formalogix-api-config
  namespace: formalogix
data:
  PORT: "3000"
  EMAIL_HOST: "mail.formalogix.com"
  EMAIL_PORT: "587"
  CORS_ORIGINS: "http://localhost:4321,http://localhost:4322,https://formalogix.com,https://www.formalogix.com,https://flickflauder.com,https://www.flickflauder.com,https://*.pages.dev"
