apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: formalogix-api
  namespace: formalogix
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - forms.flickflauder.com
    secretName: forms-flickflauder-tls
  rules:
  - host: forms.flickflauder.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: formalogix-api
            port:
              number: 80
